# Generated by Django 4.2.23 on 2025-08-28 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(help_text='One ingredient per line')),
                ('steps', models.TextField(help_text='One step per line, optionally numbered')),
                ('hero_image', models.URLField(blank=True, help_text='Link to a recipe image')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('servings', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('serving_display', models.CharField(blank=True, help_text='Shown in lists, e.g. "1 serving", "1 wrap", "4 meatballs"', max_length=100)),
                ('prep_minutes', models.PositiveSmallIntegerField(default=0)),
                ('cook_minutes', models.PositiveSmallIntegerField(default=0)),
                ('calories_kcal', models.PositiveSmallIntegerField(default=0)),
                ('protein_g', models.PositiveSmallIntegerField(default=0)),
                ('fat_g', models.PositiveSmallIntegerField(default=0)),
                ('carbs_g', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
